/**
 * This code was generated by Builder.io.
 */
import React from "react";

function DispatchedTrucks() {
  return (
    <div className="flex flex-col  w-4.9/12 max-md:ml-0 max-md:w-full">
      <div className="flex overflow-hidden flex-col items-start px-6  pt-5 pb-10 mx-auto w-full font-medium bg-white rounded-3xl leading-[66px] max-md:px-5 max-md:mt-10 ">
        <h2 className="text-2xl font-bold text-gray-900 py-1.5">Dispatched Trucks</h2>
        <div className="flex z-10 gap-3 self-stretch -mt-2.5 text-base text-black ">
          <div className="grow mt-2 md:mt-2 lg:mt-4 ">WB134** Just Dispatched</div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/fcba1dfc571c22c8062df839fc47b6df67cd6cb6090b9e4b2a09e18f2800079a?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c"
            className="object-contain shrink-0 my-auto w-10 aspect-square mt-2.5"
            alt=""
          />
        </div>
        <div className="mt-0 text-xs text-center text-green-500 mt-2 md:mt-2 lg:mt-1 mx-2">
          Updated Just Now
        </div>
      </div>
    </div>
  );
}

export default DispatchedTrucks;
