/**
 * This code was generated by Builder.io.
 */
import React from "react";

function LiveFireReports() {
  return (
    <div className="flex flex-col w-4.9/12 max-md:ml-0 max-md:w-full mr-4">
      <div className="flex overflow-hidden flex-col items-start px-6 pt-5 pb-10 mx-auto w-full font-medium bg-white rounded-3xl leading-[66px] max-md:px-5 max-md:mt-10 ">
        <h2 className="text-2xl font-bold text-gray-900">Live Fire Reports</h2>
        <div className="flex z-10 gap-10 self-stretch -mt-4 text-base  text-black">
          <div className="grow shrink w-[145px]  md:mt-2 lg:mt-7">Reported Today - 11</div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/3459cd6e364d86d389b57d5d55161538eb2b1a027022482394fc31182146bc88?placeholderIfAbsent=true&apiKey=f2f1eca11c22487684e8fe7fa994306c"
            className="object-contain shrink-0 my-auto w-10 aspect-square "
            alt=""
          />
        </div>
        <div className="z-10 mt-0 text-xs text-center text-green-500  md:mt-2 lg:mt-5">
          Updated Just Now
        </div>
      </div>
    </div>
  );
}

export default LiveFireReports;
