/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TruckManagement() {
  const trucks = [
    { number: "WB124**", location: "L1", status: "On Service" },
    { number: "WB224**", location: "L3", status: "Returned" },
    { number: "WB134**", location: "L2", status: "On Service" },
  ];

  return (
    <section className="flex overflow-hidden flex-col py-8 pl-8 rounded-3xl bg-slate-100 max-md:pl-5 max-md:max-w-full">
      <h2 className="self-start text-4xl font-bold leading-none text-gray-900">
        Truck Management
      </h2>
      <div className="flex overflow-hidden flex-col items-center pt-5 pb-11 mt-7 ml-4 w-full text-xl leading-9 text-black bg-white rounded-3xl max-md:max-w-full">
        <div className="flex gap-10 max-w-full w-[862px]">
          <div>Truck No.</div>
          <div className="grow shrink w-[109px]">Truck PL No.</div>
          <div className="grow shrink w-[116px]">Last Location</div>
          <div>Status</div>
        </div>
        <div className="flex shrink-0 self-stretch mt-2 h-px bg-slate-200 max-md:max-w-full" />
        <div className="flex flex-wrap gap-5 justify-between mt-4 ml-6 max-w-full text-center w-[851px]">
          {trucks.map((truck, index) => (
            <React.Fragment key={index}>
              <div className="flex flex-col items-start whitespace-nowrap max-md:hidden">
                <div>{index + 1}</div>
              </div>
              <div className="flex flex-col whitespace-nowrap">
                <div className="max-md:mr-0.5">{truck.number}</div>
              </div>
              <div className="flex flex-col whitespace-nowrap">
                <div className="self-start">{truck.location}</div>
              </div>
              <div
                className={`flex flex-col font-medium ${
                  truck.status === "Returned"
                    ? "text-blue-700"
                    : "text-green-500"
                }`}
              >
                <div>{truck.status}</div>
              </div>
            </React.Fragment>
          ))}
        </div>
      </div>
    </section>
  );
}

export default TruckManagement;
