/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Updates() {
  const updates = [
    { text: "+917679****** Just Reported", type: "rose" },
    { text: "+917679****** Just Reported", type: "rose" },
    { text: "Fire Truck - WB1424** reached to L1", type: "green" },
    { text: "Fire Truck - WB1424** reached to L1", type: "yellow" },
    { text: "+917679****** Just Reported", type: "rose" },
    { text: "Fire Truck - WB1424** reached to L1", type: "yellow" },
    { text: "Fire Truck - WB1424** reached to L1", type: "yellow" },
    { text: "Fire Truck - WB1424** reached to L1", type: "green" },
  ];

  return (
    <div className="flex flex-col ml-0 w-[33%] max-md:ml-0 max-md:w-full"> {/* Updated margin-left */}
      <div className="flex  flex-col grow px-8 pt-3 pb-16 w-full text-sm font-bold text-black bg-white rounded-2xl max-md:px-5 max-md:mt-2">
        <h2 className="self-center text-2xl text-gray-900">Updates</h2>
        {updates.map((update, index) => (
          <div
            key={index}
            className={`overflow-hidden px-12 py-2 mt-3.5 leading-9 text-center bg-${update.type}-100 rounded-3xl max-md:px-5`}
          >
            {update.text}
          </div>
        ))}
      </div>
    </div>
  );
}

export default Updates;

